import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_finalapp/generatednextwidget/generated/GeneratedMedicineamicoWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatednextwidget/generated/GeneratedNextWidget1.dart';
import 'package:flutterapp/proyecto_finalapp/generatednextwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatednextwidget/generated/GeneratedBienvenidoWidget.dart';

/* Frame next
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNextWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(0.0),
        topRight: Radius.circular(0.0),
        bottomRight: Radius.circular(20.0),
        bottomLeft: Radius.circular(0.0),
      ),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(0.0),
            topRight: Radius.circular(0.0),
            bottomRight: Radius.circular(20.0),
            bottomLeft: Radius.circular(0.0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(0.0),
                  topRight: Radius.circular(0.0),
                  bottomRight: Radius.circular(20.0),
                  bottomLeft: Radius.circular(0.0),
                ),
                child: Container(
                  color: Color.fromARGB(255, 219, 255, 252),
                ),
              ),
              Positioned(
                left: 25.632911682128906,
                top: 201.0,
                right: null,
                bottom: null,
                width: 333.2278747558594,
                height: 321.99993896484375,
                child: GeneratedMedicineamicoWidget(),
              ),
              Positioned(
                left: 251.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 49.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 293.0,
                top: 770.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 41.0,
                child: GeneratedNextWidget1(),
              ),
              Positioned(
                left: 100.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 44.0,
                child: GeneratedBienvenidoWidget(),
              )
            ]),
      ),
    ));
  }
}
