import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget5/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget5/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget5/generated/GeneratedHiWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget5/generated/GeneratedVITAMINAB12\$90Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget5/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget5/generated/GeneratedCboost\$70Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget5/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget5/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget5/generated/GeneratedPersonsharpWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget5/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget5/generated/GeneratedMenuinferiorWidget5.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget5/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget5/generated/GeneratedPopularWidget.dart';

/* Frame inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(40.0),
        topRight: Radius.circular(0.0),
        bottomRight: Radius.circular(0.0),
        bottomLeft: Radius.circular(0.0),
      ),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(40.0),
            topRight: Radius.circular(0.0),
            bottomRight: Radius.circular(0.0),
            bottomLeft: Radius.circular(0.0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(40.0),
                  topRight: Radius.circular(0.0),
                  bottomRight: Radius.circular(0.0),
                  bottomLeft: Radius.circular(0.0),
                ),
                child: Container(
                  color: Color.fromARGB(255, 240, 240, 240),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 142.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 159.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 30.0,
                child: GeneratedHiWidget(),
              ),
              Positioned(
                left: 301.0,
                top: 71.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 42.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 309.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 32.0,
                child: GeneratedPersonsharpWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 173.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 116.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 28.0,
                child: GeneratedPopularWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 154.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 215.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 154.0,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 534.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 154.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 215.0,
                top: 534.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 154.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 662.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 18.0,
                child: GeneratedCboost$70Widget(),
              ),
              Positioned(
                left: 221.0,
                top: 662.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 16.0,
                child: GeneratedVITAMINAB12$90Widget(),
              ),
              Positioned(
                left: -12.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 75.0,
                child: GeneratedMenuinferiorWidget5(),
              )
            ]),
      ),
    ));
  }
}
