import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedMenuinferiorWidget3.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedRectangle49Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/Generated335382Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedEXCEDRINMIGRANA24CAPSULAS_600x2Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedCOMPRADOWidget1.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedCOMPRADOWidget5.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedRectangle51Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedRectangle47Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedQuandotomarparacetamolouibuprofeno_19216_l2Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedQuandotomarparacetamolouibuprofeno_21584_l2Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedRectangle50Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedRectangle48Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedRectangle32Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedLiferpalmd_dualgos_paracetamolibuprofeno_20tabletas2Wid.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedRectangle52Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedCOMPRADOWidget3.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedHISTORIALWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedCOMPRADOWidget2.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedRectangle36Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedCOMPRADOWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/Generated81K8jGi8C9L2Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedcompraswidget6/generated/GeneratedCOMPRADOWidget4.dart';

/* Frame compras
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedComprasWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 229, 245, 250),
                ),
              ),
              Positioned(
                left: -12.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 75.0,
                child: GeneratedMenuinferiorWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 77.0,
                child: GeneratedRectangle30Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 138.0,
                child: GeneratedRectangle31Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 140.0,
                child: GeneratedRectangle32Widget(),
              ),
              Positioned(
                left: 212.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 140.0,
                child: GeneratedRectangle34Widget(),
              ),
              Positioned(
                left: 212.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 140.0,
                child: GeneratedRectangle33Widget(),
              ),
              Positioned(
                left: 45.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 140.0,
                child: GeneratedRectangle35Widget(),
              ),
              Positioned(
                left: 212.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 140.0,
                child: GeneratedRectangle36Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 36.0,
                child: GeneratedRectangle47Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 36.0,
                child: GeneratedRectangle49Widget(),
              ),
              Positioned(
                left: 213.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 36.0,
                child: GeneratedRectangle50Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 36.0,
                child: GeneratedRectangle51Widget(),
              ),
              Positioned(
                left: 212.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 36.0,
                child: GeneratedRectangle52Widget(),
              ),
              Positioned(
                left: 134.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 15.0,
                child: GeneratedHISTORIALWidget(),
              ),
              Positioned(
                left: 225.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 70.68390655517578,
                child: Generated81K8jGi8C9L2Widget(),
              ),
              Positioned(
                left: 72.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 29.0,
                child: GeneratedCOMPRADOWidget(),
              ),
              Positioned(
                left: 237.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 29.0,
                child: GeneratedCOMPRADOWidget1(),
              ),
              Positioned(
                left: 242.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 29.0,
                child: GeneratedCOMPRADOWidget2(),
              ),
              Positioned(
                left: 68.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 29.0,
                child: GeneratedCOMPRADOWidget3(),
              ),
              Positioned(
                left: 68.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 29.0,
                child: GeneratedCOMPRADOWidget4(),
              ),
              Positioned(
                left: 59.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 56.53845977783203,
                child: Generated335382Widget(),
              ),
              Positioned(
                left: 225.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 61.982906341552734,
                child:
                    GeneratedQuandotomarparacetamolouibuprofeno_19216_l2Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 64.69902801513672,
                child: GeneratedEXCEDRINMIGRANA24CAPSULAS_600x2Widget(),
              ),
              Positioned(
                left: 225.0,
                top: 509.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 60.5203742980957,
                child:
                    GeneratedQuandotomarparacetamolouibuprofeno_21584_l2Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 92.0,
                child:
                    GeneratedLiferpalmd_dualgos_paracetamolibuprofeno_20tabletas2Wid(),
              ),
              Positioned(
                left: 212.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 36.0,
                child: GeneratedRectangle48Widget(),
              ),
              Positioned(
                left: 238.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 29.0,
                child: GeneratedCOMPRADOWidget5(),
              )
            ]),
      ),
    ));
  }
}
