import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_finalapp/generatedmenuinferiorwidget/generated/GeneratedBuscadorWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedmenuinferiorwidget/generated/GeneratedMaskGroupWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedmenuinferiorwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedmenuinferiorwidget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedmenuinferiorwidget/generated/GeneratedUsuarioWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedmenuinferiorwidget/generated/GeneratedComprasWidget.dart';

/* Instance Menu inferior
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuinferiorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 400.0,
      height: 75.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 400.0,
              height: 75.0,
              child: GeneratedRectangle4Widget(),
            ),
            Positioned(
              left: 23.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 25.0,
              height: 44.0,
              child: GeneratedHomeWidget(),
            ),
            Positioned(
              left: 126.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 43.0,
              height: 43.0,
              child: GeneratedBuscadorWidget(),
            ),
            Positioned(
              left: 237.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 44.0,
              child: GeneratedComprasWidget(),
            ),
            Positioned(
              left: 343.0,
              top: 17.0,
              right: null,
              bottom: null,
              width: 33.0,
              height: 45.0,
              child: GeneratedUsuarioWidget(),
            ),
            Positioned(
              left: 171.0,
              top: -101.0,
              right: null,
              bottom: null,
              width: 377.0,
              height: 500.0,
              child: GeneratedMaskGroupWidget(),
            )
          ]),
    ));
  }
}
