import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_finalapp/generatedloginwidget/generated/GeneratedIngresatuinformacinWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedloginwidget/generated/GeneratedInputWidget2.dart';
import 'package:flutterapp/proyecto_finalapp/generatedloginwidget/generated/GeneratedPHARMACYWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedloginwidget/generated/GeneratedBotonWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedloginwidget/generated/Generated747NDboAWNYWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedloginwidget/generated/GeneratedInputWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedloginwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedloginwidget/generated/GeneratedInputWidget1.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: -3.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 500.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 100.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 44.0,
                child: GeneratedPHARMACYWidget(),
              ),
              Positioned(
                left: 86.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 204.0,
                height: 26.0,
                child: GeneratedIngresatuinformacinWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 442.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 41.0,
                child: GeneratedInputWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 41.0,
                child: GeneratedInputWidget1(),
              ),
              Positioned(
                left: 17.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 42.0,
                child: GeneratedInputWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 687.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedBotonWidget(),
              ),
              Positioned(
                left: 1.0,
                top: -200.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 512.0,
                child: Generated747NDboAWNYWidget(),
              )
            ]),
      ),
    ));
  }
}
