import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget8/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget8/generated/GeneratedCorreoelectronicoWidget3.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget8/generated/GeneratedRectangle39Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget8/generated/GeneratedRectangle40Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget8/generated/GeneratedMenuinferiorWidget4.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget8/generated/GeneratedVectorWidget346.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget8/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget8/generated/GeneratedPERFILWidget.dart';

/* Frame usuario
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUsuarioWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 229, 245, 250),
                ),
              ),
              Positioned(
                left: -12.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 75.0,
                child: GeneratedMenuinferiorWidget4(),
              ),
              Positioned(
                left: 134.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 106.99999237060547,
                height: 109.0,
                child: GeneratedVectorWidget346(),
              ),
              Positioned(
                left: 55.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 35.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 34.0,
                child: GeneratedRectangle38Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 133.0,
                child: GeneratedRectangle39Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 473.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 167.0,
                child: GeneratedRectangle40Widget(),
              ),
              Positioned(
                left: 69.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 23.0,
                child: GeneratedCorreoelectronicoWidget3(),
              ),
              Positioned(
                left: 148.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 40.0,
                child: GeneratedPERFILWidget(),
              )
            ]),
      ),
    ));
  }
}
