import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedCajadepastillasExcedrinWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle45Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle42Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedMenuinferiorWidget2.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedQuandotomarparacetamolouibuprofeno_21584_l1Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedCajadepastillasTylenolWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle41Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/Generated81K8jGi8C9L1Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedCajadepastillasXL3XtraWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/Generated\$90Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/Generated\$40Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle44Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedLiferpalmd_dualgos_paracetamolibuprofeno_20tabletas1Wid.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedCajadepastillasAmplexWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedCajadepastillasAdvilWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/Generated\$80Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/Generated\$90Widget1.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedQuandotomarparacetamolouibuprofeno_19216_l1Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedCajadepastillasDualgosWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/Generated\$50Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/Generated335381Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle46Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedSearchcircleWidget3.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedEXCEDRINMIGRANA24CAPSULAS_600x1Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/Generated\$30Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedproductoswidget2/generated/GeneratedRectangle23Widget.dart';

/* Frame productos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProductosWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(40.0),
        topRight: Radius.circular(0.0),
        bottomRight: Radius.circular(0.0),
        bottomLeft: Radius.circular(0.0),
      ),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(40.0),
            topRight: Radius.circular(0.0),
            bottomRight: Radius.circular(0.0),
            bottomLeft: Radius.circular(0.0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(40.0),
                  topRight: Radius.circular(0.0),
                  bottomRight: Radius.circular(0.0),
                  bottomLeft: Radius.circular(0.0),
                ),
                child: Container(
                  color: Color.fromARGB(255, 240, 240, 240),
                ),
              ),
              Positioned(
                left: -12.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 75.0,
                child: GeneratedMenuinferiorWidget2(),
              ),
              Positioned(
                left: 12.0,
                top: 156.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 85.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 85.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 12.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 85.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 85.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 544.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 85.0,
                child: GeneratedRectangle22Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 641.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 85.0,
                child: GeneratedRectangle23Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 142.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 71.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 37.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 313.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedSearchcircleWidget3(),
              ),
              Positioned(
                left: 27.0,
                top: 167.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 64.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 68.0,
                child: GeneratedGroup11Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 65.0,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 459.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 63.0,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 63.0,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 63.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 257.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 32.0,
                child: GeneratedRectangle41Widget(),
              ),
              Positioned(
                left: 255.0,
                top: 282.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 32.0,
                child: GeneratedRectangle42Widget(),
              ),
              Positioned(
                left: 257.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 32.0,
                child: GeneratedRectangle43Widget(),
              ),
              Positioned(
                left: 255.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 32.0,
                child: GeneratedRectangle44Widget(),
              ),
              Positioned(
                left: 255.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 32.0,
                child: GeneratedRectangle45Widget(),
              ),
              Positioned(
                left: 257.0,
                top: 668.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 32.0,
                child: GeneratedRectangle46Widget(),
              ),
              Positioned(
                left: 280.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 40.0,
                child: Generated$50Widget(),
              ),
              Positioned(
                left: 278.0,
                top: 282.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 40.0,
                child: Generated$80Widget(),
              ),
              Positioned(
                left: 281.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 40.0,
                child: Generated$90Widget(),
              ),
              Positioned(
                left: 281.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 40.0,
                child: Generated$40Widget(),
              ),
              Positioned(
                left: 280.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 40.0,
                child: Generated$30Widget(),
              ),
              Positioned(
                left: 281.0,
                top: 668.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 40.0,
                child: Generated$90Widget1(),
              ),
              Positioned(
                left: 28.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 61.157894134521484,
                child:
                    GeneratedQuandotomarparacetamolouibuprofeno_19216_l1Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 57.55555725097656,
                child:
                    GeneratedQuandotomarparacetamolouibuprofeno_21584_l1Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 459.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 69.39306640625,
                child: Generated81K8jGi8C9L1Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 63.62403106689453,
                child: GeneratedEXCEDRINMIGRANA24CAPSULAS_600x1Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 54.653846740722656,
                child: Generated335381Widget(),
              ),
              Positioned(
                left: 135.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 56.0,
                child: GeneratedCajadepastillasDualgosWidget(),
              ),
              Positioned(
                left: 133.0,
                top: 274.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 56.0,
                child: GeneratedCajadepastillasAdvilWidget(),
              ),
              Positioned(
                left: 108.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 59.0,
                child: GeneratedCajadepastillasTylenolWidget(),
              ),
              Positioned(
                left: 135.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 56.0,
                child: GeneratedCajadepastillasXL3XtraWidget(),
              ),
              Positioned(
                left: 131.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 56.0,
                child: GeneratedCajadepastillasExcedrinWidget(),
              ),
              Positioned(
                left: 135.0,
                top: 668.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 56.0,
                child: GeneratedCajadepastillasAmplexWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 69.0,
                child:
                    GeneratedLiferpalmd_dualgos_paracetamolibuprofeno_20tabletas1Wid(),
              )
            ]),
      ),
    ));
  }
}
