import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_finalapp/generatedinputwidget3/generated/GeneratedRectangle2Widget3.dart';
import 'package:flutterapp/proyecto_finalapp/generatedinputwidget3/generated/GeneratedCorreoelectronicoWidget2.dart';

/* Component Input
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 340.0,
      height: 41.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 340.0,
              height: 41.0,
              child: GeneratedRectangle2Widget3(),
            ),
            Positioned(
              left: 8.0,
              top: 7.516666889190674,
              right: null,
              bottom: null,
              width: 170.0,
              height: 14.983333587646484,
              child: GeneratedCorreoelectronicoWidget2(),
            )
          ]),
    ));
  }
}
